/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 			*/
/*  Created On : 26-Apr-2017 12:25:04 AM 								*/
/*  DBMS       : MySql 																	*/
/* ---------------------------------------------------- */
SET FOREIGN_KEY_CHECKS=0;
/* Drop Data Base */
DROP DATABASE IF EXISTS biblioteca;
/* Create Data Base */
CREATE DATABASE biblioteca;
USE biblioteca;
/* Create Tables */
CREATE TABLE `persona` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`ci` INT NOT NULL,
	`apellidos` VARCHAR(100) NOT NULL,
	`nombres` VARCHAR(100) NOT NULL,
	`fecha_nacimiento` DATE NOT NULL,
	`direccion` VARCHAR(100) NOT NULL,
	`sexo` CHAR(1) NOT NULL,
	`telefono` INT NOT NULL,
	CONSTRAINT `PK_persona` PRIMARY KEY (`id`)
);
CREATE TABLE `libro` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`titulo` VARCHAR(100) NOT NULL,
	`isbn` VARCHAR(50) NOT NULL,
	`descripcion` VARCHAR(100) NOT NULL,
	`fecha_lanzamiento` DATE NOT NULL,
	`idioma` VARCHAR(50) NOT NULL,
	`paginas` INT NOT NULL,
	`edicion` INT NOT NULL,
	`id_editorial` INT 	 NULL,
	`id_categoria` INT 	 NULL,
	CONSTRAINT `PK_libro` PRIMARY KEY (`id`)
);
CREATE TABLE `lector` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`fecha_afiliacion` DATE NOT NULL,
	`id_persona` INT 	 NULL,
	CONSTRAINT `PK_lector` PRIMARY KEY (`id`)
);
CREATE TABLE `ficha_prestramo` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`fecha_prestamo` DATE NOT NULL,
	`fecha_devolucion` DATE NOT NULL,
	`devuelto` BOOL NOT NULL,
	`id_lector` INT 	 NULL,
	`id_bibliotecario` INT 	 NULL,
	CONSTRAINT `PK_ficha_prestramo` PRIMARY KEY (`id`)
);
CREATE TABLE `ejemplar` (
	`id_libro` INT NOT NULL,
	`nro_ejemplar` INT NOT NULL,
	CONSTRAINT `PK_ejemplar` PRIMARY KEY (`id_libro`,`nro_ejemplar`)
);
CREATE TABLE `editorial` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NOT NULL,
	`telefono` INT NOT NULL,
	`direccion` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_editorial` PRIMARY KEY (`id`)
);
CREATE TABLE `detalle_prestamo` (
	`id_libro` INT NOT NULL,
	`nro_ejemplar` INT NOT NULL,
	`id_prestamo` INT NOT NULL,
	CONSTRAINT `PK_detalle_prestamo` PRIMARY KEY (`id_libro`,`nro_ejemplar`,`id_prestamo`)
);
CREATE TABLE `categoria` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NOT NULL,
	`descripcion` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_categoria` PRIMARY KEY (`id`)
);
CREATE TABLE `bibliotecario` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`ano_contratacion` INT NOT NULL,
	`id_persona` INT 	 NULL,
	CONSTRAINT `PK_bibliotecario` PRIMARY KEY (`id`)
);
CREATE TABLE `autoria` (
	`id_libro` INT NOT NULL,
	`id_autor` INT NOT NULL,
	CONSTRAINT `PK_autoria` PRIMARY KEY (`id_libro`,`id_autor`)
);
CREATE TABLE `autor` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NOT NULL,
	`pais_origen` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_autor` PRIMARY KEY (`id`)
);
/* Create Indexes, Uniques, Checks */
ALTER TABLE `libro`
 ADD INDEX `IXFK_libro_categoria` (`id_categoria` ASC);
ALTER TABLE `libro`
 ADD INDEX `IXFK_libro_editorial` (`id_editorial` ASC);
ALTER TABLE `lector`
 ADD INDEX `IXFK_lector_persona` (`id_persona` ASC);
ALTER TABLE `ficha_prestramo`
 ADD INDEX `IXFK_ficha_prestramo_bibliotecario` (`id_bibliotecario` ASC);
ALTER TABLE `ficha_prestramo`
 ADD INDEX `IXFK_ficha_prestramo_lector` (`id_lector` ASC);
ALTER TABLE `ejemplar`
 ADD INDEX `IXFK_ejemplar_libro` (`id_libro` ASC);
ALTER TABLE `detalle_prestamo`
 ADD INDEX `IXFK_detalle_prestamo_ejemplar` (`id_libro` ASC,`nro_ejemplar` ASC);
ALTER TABLE `detalle_prestamo`
 ADD INDEX `IXFK_detalle_prestamo_ficha_prestramo` (`id_prestamo` ASC);
ALTER TABLE `bibliotecario`
 ADD INDEX `IXFK_bibliotecario_persona` (`id_persona` ASC);
ALTER TABLE `autoria`
 ADD INDEX `IXFK_autoria_autor` (`id_autor` ASC);
ALTER TABLE `autoria`
 ADD INDEX `IXFK_autoria_libro` (`id_libro` ASC);
/* Create Foreign Key Constraints */
ALTER TABLE `libro`
 ADD CONSTRAINT `FK_libro_categoria`
	FOREIGN KEY (`id_categoria`) REFERENCES `categoria` (`id`) ON DELETE Set Null ON UPDATE Cascade;
ALTER TABLE `libro`
 ADD CONSTRAINT `FK_libro_editorial`
	FOREIGN KEY (`id_editorial`) REFERENCES `editorial` (`id`) ON DELETE Set Null ON UPDATE Cascade;
ALTER TABLE `lector`
 ADD CONSTRAINT `FK_lector_persona`
	FOREIGN KEY (`id_persona`) REFERENCES `persona` (`id`) ON DELETE Cascade ON UPDATE Cascade;
ALTER TABLE `ficha_prestramo`
 ADD CONSTRAINT `FK_ficha_prestramo_bibliotecario`
	FOREIGN KEY (`id_bibliotecario`) REFERENCES `bibliotecario` (`id`) ON DELETE Set Null ON UPDATE Cascade;
ALTER TABLE `ficha_prestramo`
 ADD CONSTRAINT `FK_ficha_prestramo_lector`
	FOREIGN KEY (`id_lector`) REFERENCES `lector` (`id`) ON DELETE Set Null ON UPDATE Cascade;
ALTER TABLE `ejemplar`
 ADD CONSTRAINT `FK_ejemplar_libro`
	FOREIGN KEY (`id_libro`) REFERENCES `libro` (`id`) ON DELETE No Action ON UPDATE Cascade;
ALTER TABLE `detalle_prestamo`
 ADD CONSTRAINT `FK_detalle_prestamo_ejemplar`
	FOREIGN KEY (`id_libro`,`nro_ejemplar`) REFERENCES `ejemplar` (`id_libro`,`nro_ejemplar`) ON DELETE Cascade ON UPDATE Cascade;
ALTER TABLE `detalle_prestamo`
 ADD CONSTRAINT `FK_detalle_prestamo_ficha_prestramo`
	FOREIGN KEY (`id_prestamo`) REFERENCES `ficha_prestramo` (`id`) ON DELETE Cascade ON UPDATE Cascade;
ALTER TABLE `bibliotecario`
 ADD CONSTRAINT `FK_bibliotecario_persona`
	FOREIGN KEY (`id_persona`) REFERENCES `persona` (`id`) ON DELETE Cascade ON UPDATE Cascade;
ALTER TABLE `autoria`
 ADD CONSTRAINT `FK_autoria_autor`
	FOREIGN KEY (`id_autor`) REFERENCES `autor` (`id`) ON DELETE Cascade ON UPDATE Cascade;
ALTER TABLE `autoria`
 ADD CONSTRAINT `FK_autoria_libro`
	FOREIGN KEY (`id_libro`) REFERENCES `libro` (`id`) ON DELETE Cascade ON UPDATE Cascade;
SET FOREIGN_KEY_CHECKS=1;
